### ISSUE TITLE
This can be used to cheat on exams

### ISSUE THREAD

**Issue by esrrhs** [Michaelangel007/nanofont3x4#2]
a small paper with all answer. lol

**Comment by Michaelangel007** [comment]
Any tool can be used or abused. Around 40,000+ people each year in the US due to vehicle accidents. Do we ban vehicles because a _few_ misuse them? No. We have to draw the line (of common sense) _somewhere_ else _everything_ would eventually get banned.

There is nothing I can do to stop someone using this font dedicated to cheating. Thankfully I don't have to; karma will take care of people lacking integrity for themselves and lacking respect for others.
